version: "3.8"

services:

  app:
    build: .
    ports:
      - "8082:8081"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 747733
      SPRING_DATA_REDIS_HOST: redis

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 747733
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"